# Generated by Django 4.2.3 on 2023-07-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registration',
            name='module',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
